Migration worker error fix.
requests.exceptions.SSLError: HTTPSConnectionPool(host='es-cluster-es-http.elastic.svc.cluster.local', port=9200): Max retries exceeded with url: /638ee.tracardi-task/_doc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))